version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 dora_metrics.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: DORA_METRICS
    ports:
      - "3307:3306"  # Changed the host port to 3307
