service: dora-metrics

provider:
  name: aws
  runtime: python3.9
  environment:
    DB_NAME: ${env:DB_NAME}
    DB_USER: ${env:DB_USER}
    DB_PASSWORD: ${env:DB_PASSWORD}
    DB_HOST: ${env:DB_HOST}
    DB_PORT: ${env:DB_PORT, '3306'}
    SECRET_KEY: ${env:SECRET_KEY}

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}

plugins:
  - serverless-python-requirements
  - serverless-offline
  
custom:
  pythonRequirements:
    dockerizePip: true
    layer: true
    useDocker: true

package:
  exclude:
    - node_modules/**
    - venv/**
    - .venv/**
    - __pycache__/**
